# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22e5f1f7d6de32732e7085a56ee507261e3fd27433e99482ffeefcd1821f8ceda9874c0f3436afc1e191c98979af1fe2439f0723b7aad0b7b5a40e0b70ee522f

test:
  secret_key_base: 64fa17a8cd78a9c5d1534f7ceec49c1bad3f6d379089a797c797509fc8a196b47fbee1186d45553c4c408ed98ee420af08c4c35633164e9d394c4c0a140593d3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
